In [1]:
import numpy as np

## task 5.1

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

## task 5.2

In [3]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)
w, v

(array([-1., -1.]),
 array([[1., 0.],
        [0., 1.]]))

## task 5.3

In [4]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
w, v

(array([2.00000002, 1.99999998]),
 array([[ 0.70710677, -0.70710679],
        [ 0.70710679, -0.70710677]]))

In [5]:
x = np.array([1, 1])

In [6]:
a.dot(x)

array([2, 2])

## task 5.4

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])

In [8]:
a.dot(x)

array([ -9,   9, -12])

In [9]:
w, v = np.linalg.eig(a)
w, v

(array([ 3., -3.,  3.]),
 array([[ 0.70710678, -0.70710678,  0.        ],
        [ 0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))