In [1]:
import numpy as np
import scipy.linalg

## task 6.2

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A1 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

In [3]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(A1)

(3, 3)

In [4]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
B1 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

In [5]:
np.linalg.matrix_rank(B), np.linalg.matrix_rank(B1)

(1, 2)

In [6]:
C = np.array([[1, 2, 5], [3, 1, -8]])
C1 = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

In [7]:
np.linalg.matrix_rank(C), np.linalg.matrix_rank(C1)

(2, 2)

## task 6.3

In [8]:
D = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
D1 = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

In [9]:
np.linalg.matrix_rank(D), np.linalg.matrix_rank(D1)

(4, 4)

## task 7.1

In [10]:
A = np.array([[1, 3], [-2, -4]])
A1 = np.array([[1, 7], [-2, -4]])
A2 = np.array([[1, 3], [1, 7]])

In [11]:
np.linalg.det(A), np.linalg.det(A1), np.linalg.det(A2)

(2.0, 9.999999999999998, 4.0)

In [12]:
x1 = np.linalg.det(A1)/np.linalg.det(A)
x2 = np.linalg.det(A2)/np.linalg.det(A)
x1, x2

(4.999999999999999, 2.0)

In [13]:
B = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B1 = np.array([[10, -2, 1], [1, 1, -3], [2, 4, 1]])
B2 = np.array([[2, -1, 5], [10, -2, 1], [2, 4, 1]])
B3 = np.array([[2, -1, 5], [1, 1, -3], [10, -2, 1]])

In [14]:
np.linalg.det(B), np.linalg.det(B1), np.linalg.det(B2), np.linalg.det(B3)

(42.99999999999998, 146.0, 216.00000000000006, -38.99999999999999)

In [15]:
x1 = np.linalg.det(B1)/np.linalg.det(B)
x2 = np.linalg.det(B2)/np.linalg.det(B)
x3 = np.linalg.det(B3)/np.linalg.det(B)
x1, x2, x3

(3.395348837209304, 5.023255813953492, -0.9069767441860468)

## task 7.2

In [16]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

In [17]:
L1 = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]]) # расчет в pdf
U1 = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])

In [18]:
L1.dot(U1) == A #проверка

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
P, L, U = scipy.linalg.lu(A)

L, U

(array([[1.        , 0.        , 0.        ],
        [0.66666667, 1.        , 0.        ],
        [0.33333333, 0.8       , 1.        ]]),
 array([[ 3.        , 26.        , 30.        ],
        [ 0.        , -8.33333333, -8.        ],
        [ 0.        ,  0.        ,  0.4       ]]))

In [20]:
B = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])

In [21]:
L2 = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]]) # расчет в pdf
U2 = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

In [22]:
L2.dot(U2) == B

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [23]:
P, L, U = scipy.linalg.lu(B)

L, U

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.5       ,  1.        ,  0.        ,  0.        ],
        [ 0.75      , -0.25      ,  1.        ,  0.        ],
        [ 0.25      ,  0.75      , -0.17073171,  1.        ]]),
 array([[  4.        ,  22.        ,  53.        ,  33.        ],
        [  0.        ,  -6.        , -18.5       ,  -7.5       ],
        [  0.        ,   0.        , -15.375     ,  -8.625     ],
        [  0.        ,   0.        ,   0.        ,  -0.09756098]]))

## task 7.3

In [24]:
A = np.array([[1, 3, 2], [7, 5, 11], [8, 4, 9]]) # переставила первый столбец в конец

In [25]:
L3 = np.array([[1, 0, 0], [7, 1, 0], [8, 5/4, 1]]) # расчет в pdf
U3 = np.array([[1, 3, 2], [0, -16, -3], [0, 0, -13/4]])

In [26]:
L3.dot(U3) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
b = np.array([1, -6, -5])

In [28]:
# Ly = b

In [29]:
y = np.linalg.solve(L3, b)
y

array([  1.  , -13.  ,   3.25])

In [30]:
# Ux = y

In [31]:
x2, x3, x1 = np.linalg.solve(U3, y)
x1, x2, x3

(-1.0, 0.0, 1.0)

## task 7.4

In [32]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

In [33]:
L4 = np.array([[9, 0, 0], [-5, 5, 0], [5, 2, 3]]) # расчет в pdf

In [34]:
L4T = L4.T
L4T

array([[ 9, -5,  5],
       [ 0,  5,  2],
       [ 0,  0,  3]])

In [35]:
L4.dot(L4T) == A

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [36]:
y = np.linalg.solve(L4, b)
y

array([ 59., -33., -12.])

In [37]:
x = np.linalg.solve(L4T, y)
x

array([ 6., -5., -4.])

In [38]:
L = np.linalg.cholesky(A)
L

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

## task 7.5

In [39]:
def CholeskyDecomp(A):
    n = len(A[0])
    L = np.zeros((n, n))
    for i in range(0, n):
        for j in range(0, i):
            tmp = 0
            for k in range(0, j):
                tmp += L[i][k] * L[j][k]
                k += 1
            L[i][j] = (A[i][j] - tmp) / L[j][j]
            j += 1
        tmp = A[i][i]
        for k in range(0, i):
            tmp -= L[i][k] * L[i][k]
            k += 1
        L[i][i] = np.sqrt(tmp)
        i += 1
    return L

In [40]:
def CholeskySystemSolve(A, b):
    if (np.linalg.det(A) != 0) & (np.linalg.eig(A)[0] >= 0).all() & (A == A.T).all():
        L = CholeskyDecomp(A)
        y = np.linalg.solve(L, b)
        x = np.linalg.solve(L.T, y)
        return x
    elif np.linalg.det(A) == 0:
        return 'Matrix is degenerate'
    elif (np.linalg.eig(A)[0] < 0).any():
        return 'Matrix is not positive definite'
    elif (A3 != A3.T).any():
        return 'Matrix is not symmetric'
    else:
        return 'Something goes wrong'

In [41]:
A1 = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b1 = np.array([531, -460, 193])

In [42]:
CholeskySystemSolve(A1, b1)

array([ 6., -5., -4.])

In [43]:
A2 = np.array([[6.25, -1, 0.5], [-1, 5, 2.12], [0.5, 2.12, 3.6]])
b2 = np.array([7.5, -8.68, -0.24])

In [44]:
CholeskySystemSolve(A2, b2)

array([ 0.8, -2. ,  1. ])

In [45]:
A3 = np.array([[1, 3, 2], [7, 5, 11], [8, 4, 9]])
b3 = np.array([1, -6, -5])

In [46]:
CholeskySystemSolve(A3, b3)

'Matrix is not positive definite'