In [1]:
import numpy as np

## task 3.2

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [3]:
A + B

array([[ 5, -3],
       [ 3,  5]])

In [4]:
A.dot(B)

array([[  4, -11],
       [ 12,  -3]])

In [5]:
B.dot(A)

array([[ 1, -8],
       [15,  0]])

## task 3.3

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

In [7]:
3 * A - 2 * B + 4 * C

array([[ 11,  -5],
       [  9, -12]])

## task 3.4

In [8]:
A = np.array([[4, 1], [5, -2], [2, 3]])

In [9]:
AT = A.T
AT

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [10]:
A.dot(AT)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [11]:
AT.dot(A)

array([[45,  0],
       [ 0, 14]])

## task 3.4

In [12]:
def mult(A, B):
    return [[sum(a * b for a, b in zip(row_a, col_b)) for col_b in zip(*B)] for row_a in A]

In [13]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

In [14]:
mult(A, B)

[[4, -11], [12, -3]]

## task 4.1

In [15]:
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
np.linalg.det(B)

180.0

In [17]:
np.linalg.det(C)

-9.51619735392994e-16

## task 4.3

In [18]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

In [19]:
np.linalg.det(A)

0.0

## task 4.4

In [20]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])

In [21]:
np.linalg.matrix_rank(A)

2

In [22]:
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])

In [23]:
np.linalg.matrix_rank(B)

3